#
# Deploys the gateway microservice to Kubernetes.
#
# To deploy:
#
# export CONTAINER_REGISTRY=<your-container-registry>
# export VERSION=<the-version-to-deploy>
# npx figit ./scripts/kubernetes/gateway.yaml --output yaml | kubectl apply -f -
#
# Note:
#
# Figit is used to inject environment variables into the Kubernetes Yaml configuration file.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "rajhisaifeddine/ephemeral-envs-gateway:c14e9ccc95e5138c496e0e71413a7aa4cccaddee"
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "4000"
            - name: DBHOST
              value: mongodb://db.default.svc.cluster.local:27017
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  template:
    spec:
      containers:
        - image: 'rajhisaifeddine/ephemeral-envs-gateway:c14e9ccc95e5138c496e0e71413a7aa4cccaddee'
