#
# Deploys the worker microservice to Kubernetes.
#
# To deploy:
#
#
# To deploy:
#
# export CONTAINER_REGISTRY=<your-container-registry>
# export VERSION=<the-version-to-deploy>
# npx figit ./scripts/kubernetes/worker.yaml --output yaml | kubectl apply -f -
#
# Note:
#
# Figit is used to inject environment variables into the Kubernetes Yaml configuration file.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "rajhisaifeddine/ephemeral-envs-worker:ce4d94f7961cc870b0c1d21d8ce21e8beb0d1e77"
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "4000"
            - name: DBHOST
              value: mongodb://db:27017
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  template:
    spec:
      containers:
        - image: rajhisaifeddine/ephemeral-envs-worker:ce4d94f7961cc870b0c1d21d8ce21e8beb0d1e77
          env:
            - null
            - value: mongodb://db:27017
